### PR TITLE
Overscroll Fixed for Navbar Menu

### PR DESCRIPTION
**Pull request by Shivang-Bhandari**
@jig08 Issue fixed for the menu items as discussed.
The menu can be tested at : Shivang-Bhandari.github.io/events.fossasia.org

### CODE REVIEW

**Comment by Shivang-Bhandari** [comment]
@mariobehling Sir This repo also had the same issue as of fossasia.org for the dropdown menu in the navigation bar. I have fixed it in this pr as in fossasia.org repo. The link for testing is provided in the comment above.

**Comment by jigyasa-grover** [comment]
@Shivang-Bhandari Squash the commits pls.

**Comment by Shivang-Bhandari** [comment]
@jig08 done

**Comment by Shivang-Bhandari** [comment]
@jig08 is it working fine?

**Comment by mariobehling** [comment]
@Shivang-Bhandari Thank you. Some items have changed in the meantime. Would be great if you could help with this issue: https://github.com/fossasia/fossasia.org/issues/152

**Pull request closed without merging**
