### PR TITLE
Updated Hyperlinks #18

### PR DESCRIPTION
**Pull request by satya-vinay**
This Fixes the issue #18

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
1. Don't link to index.html - link to apply/
2. Fox "//" in links

**Review by amrs-tech — CHANGES_REQUESTED** [review]
I think there's no need for double slash (//) in the hyperlinks that have been changed.

**Comment by satya-vinay** [comment]
@amrs-tech When to use double slash(//) in hyperlinks ?

**Comment by amrs-tech** [comment]
Actually I think double slash is unnecessary. The trailing slash refers to a directory in the web server. Single slash is generally used in URLs. To my knowledge, double slash is used for mentioning URLs in Python program for solving encoding problems to use symbols. 
Correct me if I'm wrong. :)

**Comment by satya-vinay** [comment]
@amrs-tech so should I remove those double slash ?

**Comment by mariobehling** [comment]
Fixed elsewhere. Thanks.

**Pull request closed without merging**
